"""Add shipment tracking tables

Revision ID: 0b6739e23b29
Revises: 
Create Date: 2026-01-04 17:29:23.341590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b6739e23b29'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipments',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('supplier', sa.String(length=200), nullable=False),
    sa.Column('warehouse', sa.String(length=200), nullable=False),
    sa.Column('route_type', sa.String(length=20), nullable=False),
    sa.Column('current_status', sa.String(length=50), nullable=True),
    sa.Column('bags_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_bags', sa.Integer(), nullable=False),
    sa.Column('total_pieces', sa.Integer(), nullable=False),
    sa.Column('google_sheets_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_shipments_created_at', 'shipments', ['created_at'], unique=False)
    op.create_index('idx_shipments_current_status', 'shipments', ['current_status'], unique=False)
    op.create_table('shipment_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('idx_shipment_history_changed_at', 'shipment_status_history', ['changed_at'], unique=False)
    op.create_index('idx_shipment_history_shipment_id', 'shipment_status_history', ['shipment_id'], unique=False)
    op.create_index(op.f('ix_shipment_status_history_id'), 'shipment_status_history', ['id'], unique=False)
    op.create_table('user_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('shipment_id', sa.String(length=50), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_logs_created_at', 'user_logs', ['created_at'], unique=False)
    op.create_index('idx_user_logs_shipment_id', 'user_logs', ['shipment_id'], unique=False)
    op.create_index('idx_user_logs_user_id', 'user_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_logs_id'), 'user_logs', ['id'], unique=False)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_index(op.f('ix_user_logs_id'), table_name='user_logs')
    op.drop_index('idx_user_logs_user_id', table_name='user_logs')
    op.drop_index('idx_user_logs_shipment_id', table_name='user_logs')
    op.drop_index('idx_user_logs_created_at', table_name='user_logs')
    op.drop_table('user_logs')
    op.drop_index(op.f('ix_shipment_status_history_id'), table_name='shipment_status_history')
    op.drop_index('idx_shipment_history_shipment_id', table_name='shipment_status_history')
    op.drop_index('idx_shipment_history_changed_at', table_name='shipment_status_history')
    op.drop_table('shipment_status_history')
    op.drop_index('idx_shipments_current_status', table_name='shipments')
    op.drop_index('idx_shipments_created_at', table_name='shipments')
    op.drop_table('shipments')
    # ### end Alembic commands ###
