"""add_supplier_warehouse_relation

Revision ID: 74931d7a0a65
Revises: e3378ea45cf7
Create Date: 2026-01-10 19:17:23.148553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74931d7a0a65'
down_revision: Union[str, None] = 'e3378ea45cf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_warehouses_id'), 'supplier_warehouses', ['id'], unique=False)
    op.create_index(op.f('ix_supplier_warehouses_supplier_id'), 'supplier_warehouses', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_supplier_warehouses_warehouse_id'), 'supplier_warehouses', ['warehouse_id'], unique=False)
    op.drop_constraint('warehouses_name_key', 'warehouses', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('warehouses_name_key', 'warehouses', ['name'])
    op.drop_index(op.f('ix_supplier_warehouses_warehouse_id'), table_name='supplier_warehouses')
    op.drop_index(op.f('ix_supplier_warehouses_supplier_id'), table_name='supplier_warehouses')
    op.drop_index(op.f('ix_supplier_warehouses_id'), table_name='supplier_warehouses')
    op.drop_table('supplier_warehouses')
    # ### end Alembic commands ###
