"""Add shipment_date and shipment_change_log

Revision ID: a3ef7d6a2cf0
Revises: 0708f64984ee
Create Date: 2026-01-07 19:50:59.775766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3ef7d6a2cf0'
down_revision: Union[str, None] = '0708f64984ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipment_change_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.String(length=50), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_change_log_changed_at', 'shipment_change_log', ['changed_at'], unique=False)
    op.create_index('idx_change_log_organization_id', 'shipment_change_log', ['organization_id'], unique=False)
    op.create_index('idx_change_log_shipment_id', 'shipment_change_log', ['shipment_id'], unique=False)
    op.create_index(op.f('ix_shipment_change_log_id'), 'shipment_change_log', ['id'], unique=False)
    op.create_index(op.f('ix_shipment_change_log_organization_id'), 'shipment_change_log', ['organization_id'], unique=False)
    op.drop_index('idx_organizations_name', table_name='organizations')
    op.drop_constraint('uq_organizations_name', 'organizations', type_='unique')
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.alter_column('product_colors', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('product_colors_organization_id_fkey', 'product_colors', type_='foreignkey')
    op.create_foreign_key(None, 'product_colors', 'organizations', ['organization_id'], ['id'])
    op.alter_column('product_models', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('product_models_organization_id_fkey', 'product_models', type_='foreignkey')
    op.create_foreign_key(None, 'product_models', 'organizations', ['organization_id'], ['id'])
    op.drop_index('idx_shipment_status_history_organization_id', table_name='shipment_status_history')
    op.create_index('idx_shipment_history_organization_id', 'shipment_status_history', ['organization_id'], unique=False)
    op.create_index(op.f('ix_shipment_status_history_organization_id'), 'shipment_status_history', ['organization_id'], unique=False)
    op.add_column('shipments', sa.Column('shipment_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_shipments_organization_id'), 'shipments', ['organization_id'], unique=False)
    op.drop_constraint('fk_shipments_organization', 'shipments', type_='foreignkey')
    op.create_foreign_key(None, 'shipments', 'organizations', ['organization_id'], ['id'])
    op.alter_column('suppliers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('suppliers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('suppliers_organization_id_fkey', 'suppliers', type_='foreignkey')
    op.create_foreign_key(None, 'suppliers', 'organizations', ['organization_id'], ['id'])
    op.create_index(op.f('ix_user_logs_organization_id'), 'user_logs', ['organization_id'], unique=False)
    op.alter_column('user_suppliers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('ix_user_suppliers_supplier_id', table_name='user_suppliers')
    op.drop_index('ix_user_suppliers_user_id', table_name='user_suppliers')
    op.drop_index('idx_users_organization_id', table_name='users')
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.drop_constraint('fk_users_organization', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'])
    op.alter_column('warehouses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('warehouses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('warehouses_organization_id_fkey', 'warehouses', type_='foreignkey')
    op.create_foreign_key(None, 'warehouses', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'warehouses', type_='foreignkey')
    op.create_foreign_key('warehouses_organization_id_fkey', 'warehouses', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.alter_column('warehouses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('warehouses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('fk_users_organization', 'users', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.create_index('idx_users_organization_id', 'users', ['organization_id'], unique=False)
    op.create_index('ix_user_suppliers_user_id', 'user_suppliers', ['user_id'], unique=False)
    op.create_index('ix_user_suppliers_supplier_id', 'user_suppliers', ['supplier_id'], unique=False)
    op.alter_column('user_suppliers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_user_logs_organization_id'), table_name='user_logs')
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.create_foreign_key('suppliers_organization_id_fkey', 'suppliers', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.alter_column('suppliers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('suppliers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'shipments', type_='foreignkey')
    op.create_foreign_key('fk_shipments_organization', 'shipments', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_shipments_organization_id'), table_name='shipments')
    op.drop_column('shipments', 'shipment_date')
    op.drop_index(op.f('ix_shipment_status_history_organization_id'), table_name='shipment_status_history')
    op.drop_index('idx_shipment_history_organization_id', table_name='shipment_status_history')
    op.create_index('idx_shipment_status_history_organization_id', 'shipment_status_history', ['organization_id'], unique=False)
    op.drop_constraint(None, 'product_models', type_='foreignkey')
    op.create_foreign_key('product_models_organization_id_fkey', 'product_models', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.alter_column('product_models', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'product_colors', type_='foreignkey')
    op.create_foreign_key('product_colors_organization_id_fkey', 'product_colors', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.alter_column('product_colors', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.create_unique_constraint('uq_organizations_name', 'organizations', ['name'])
    op.create_index('idx_organizations_name', 'organizations', ['name'], unique=False)
    op.drop_index(op.f('ix_shipment_change_log_organization_id'), table_name='shipment_change_log')
    op.drop_index(op.f('ix_shipment_change_log_id'), table_name='shipment_change_log')
    op.drop_index('idx_change_log_shipment_id', table_name='shipment_change_log')
    op.drop_index('idx_change_log_organization_id', table_name='shipment_change_log')
    op.drop_index('idx_change_log_changed_at', table_name='shipment_change_log')
    op.drop_table('shipment_change_log')
    # ### end Alembic commands ###
