"""add_fulfillments_table_and_supplier_fulfillment_relation

Revision ID: e3378ea45cf7
Revises: 9fcd469291f7
Create Date: 2026-01-10 18:13:23.534035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3378ea45cf7'
down_revision: Union[str, None] = '9fcd469291f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fulfillments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fulfillments_id'), 'fulfillments', ['id'], unique=False)
    op.create_index(op.f('ix_fulfillments_organization_id'), 'fulfillments', ['organization_id'], unique=False)
    op.create_table('supplier_fulfillments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('fulfillment_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['fulfillment_id'], ['fulfillments.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_fulfillments_fulfillment_id'), 'supplier_fulfillments', ['fulfillment_id'], unique=False)
    op.create_index(op.f('ix_supplier_fulfillments_id'), 'supplier_fulfillments', ['id'], unique=False)
    op.create_index(op.f('ix_supplier_fulfillments_supplier_id'), 'supplier_fulfillments', ['supplier_id'], unique=False)
    op.add_column('shipments', sa.Column('fulfillment', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipments', 'fulfillment')
    op.drop_index(op.f('ix_supplier_fulfillments_supplier_id'), table_name='supplier_fulfillments')
    op.drop_index(op.f('ix_supplier_fulfillments_id'), table_name='supplier_fulfillments')
    op.drop_index(op.f('ix_supplier_fulfillments_fulfillment_id'), table_name='supplier_fulfillments')
    op.drop_table('supplier_fulfillments')
    op.drop_index(op.f('ix_fulfillments_organization_id'), table_name='fulfillments')
    op.drop_index(op.f('ix_fulfillments_id'), table_name='fulfillments')
    op.drop_table('fulfillments')
    # ### end Alembic commands ###
